name: GitHub Actions - Configuração de Variável de repositório
run-name: Running - Var Repo Config
on: [push]
jobs:
    on-push:
        runs-on: ubuntu-latest
        steps:
            - name: Comentario
              run: |
                 echo "${{secrets.test_secret}}"