name: Push Template Basic 
run-name: Running - ${{github.event_name}}
on: [workflow_dispatch]
        
jobs: 
  on-workflow_dispatch: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Comentário 
        run: | 
          echo "Comentário do workflow PUSH"