name: GitHubs Actions - Jobs
run-name: Running

on: [push]

jobs:
    test_unit:
        runs-on: ubuntu-latest
        steps:
            - name: comentário
              run: |
               echo "Execução Setup"

    test_api:
        needs: test_unit
        runs-on: ubuntu-latest
        steps:
            - name: Comentário
              run: |
                echo "Execução test"

    test_ui:
        needs: test_api
        runs-on: ubuntu-latest
        steps:
            - name: Comentário
              run: |
                echo "Execução test"