name: GitHub Actions - jobs
run-name: Running 
on: [push]

jobs:
    matrix_job:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                navegador: [chrome, firefox, webkit]
                tag: [tag_1, tag_2,tag_3]
               # framework: [robot, cypress, selenium]
            fail-fast: false
        steps:
            - name: Comentário
              run: |
                echo ${{matrix.navegador}}
                echo ${{matrix.tag}}
