name: Github Actions - Workflow_dispatch 1
run-name: Running - ${{github.event_name}}
on:
    workflow_dispatch:
        inputs:
            browser:
                description: Selecione qualquer coisa
                type: string
jobs: 
  on-workflow_dispatch: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Comentário 
        run: | 
          echo "Comentário do workflow dispatch - ${{inputs.browser}}"