name: GitHub Actions - Configuração de Variável de repositório
run-name: Running - Var Repo Config
on: [push]
env: 
    variavel: "Bom dia"
    var_1: ${{secrets.TEST_SECRET}}
    var_2: ${{vars.VAR_TEST}}
jobs:
    on-push:
        runs-on: ubuntu-latest
        steps:
            - name: Comentario
              run: |
                 echo "$variavel"
                 echo "var_1"
                 echo "var_2"